### ISSUE TITLE
Webhook authentication sample code.

### ISSUE THREAD

**Issue by despian** [MicrosoftDocs/partner-rest#1]
Maybe I'm missing something but the sample code shown here does not verify the webhook received. All it does is retrieve and validate the certificate specified in the header.

Any malicious actor could just provide a valid certificate URL header and this code would accept that as a valid request.

What it should do is use the retrieved certificate to validate the signature in the Authorization header.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caab8306-10df-ffbc-e69d-d1735938fa7d
* Version Independent ID: 28e35345-2751-1aea-321e-c1a1988cfe35
* Content: [Referral connectors. - Partner](https://docs.microsoft.com/en-gb/partner/develop/referral-connectors#feedback)
* Content Source: [partner-rest/develop/referral-connectors.md](https://github.com/MicrosoftDocs/partner-rest/blob/docs/partner-rest/develop/referral-connectors.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-csp**
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by ingramleedy** [comment]
@despian Would you be available for a consulting project related to this? My email is ingram@protectedtrust.com

**Comment by despian** [comment]
The sample in the docs still contains the error described:

https://docs.microsoft.com/en-gb/partner/develop/referral-connectors#sample-function-app-code
