### ISSUE TITLE
partner-rest/develop/get-a-price-sheet.md does not match published content

### ISSUE THREAD

**Issue by RoelofSpijker** [MicrosoftDocs/partner-rest#10]
The contents of the repository for the page in the title does not match the published content on https://docs.microsoft.com/en-us/partner/develop/get-a-price-sheet. This makes it difficult to log issues against the published content.

**Comment by jasongroce** [comment]
Hello, we are archiving this repo and moving its content to the central Partner Center developer content location at https://learn.microsoft.com/en-us/partner-center/develop/get-a-price-sheet. Thank you for your feedback!
