### ISSUE TITLE
Foreign Exchange Rates - User Authentication

### ISSUE THREAD

**Issue by UsmanMohammad** [MicrosoftDocs/partner-rest#12]
I've been trying to follow this documentation: 
https://github.com/MicrosoftDocs/partner-rest/blob/docs/partner-rest/develop/get-foreign-exchange-rates.md

I've created the app registration in Active Directory, but there are no steps on how to actually authenticate/retrieve a bearer token which is then used to call the foreign exchange rate API.

What endpoint do I authenticate with in order to get the token to use in the exchange rates API?

**Comment by jasongroce** [comment]
Hello, we are archiving this repo and moving its content to the central Partner Center developer content location. For this scenario that's at https://learn.microsoft.com/en-us/partner-center/develop/partner-center-authentication. This feedback has been logged internally and we will use it to update the content in the future. Thank you for your feedback!
