### ISSUE TITLE
MS Partner API to get License subscription and pricing details

### ISSUE THREAD

**Issue by JanakarM** [MicrosoftDocs/partner-rest#13]
https://docs.microsoft.com/en-us/partner/develop/api-authentication#application-and-user-access

I've created application with permissions as mentioned in above document.

While requesting for access token, tried with following scopes one by one, with no luck.
https://api.partner.microsoft-int.com/.default 
https://reseller.microsoft.com/.default
https://api.partner.microsoft.com

When I use the token to call api, I get a AccessDenied.

[API Response](https://i.stack.imgur.com/jmIka.png)

**StackOverflow links:**
https://stackoverflow.com/questions/72830645/ms-partner-api-to-get-license-subscription-and-pricing-details
https://stackoverflow.com/questions/64783363/microsoft-partner-api-access-denied

**Comment by MSPscripts** [comment]
Hopefully you figured this out but if anyone stumbles on this, I think the scope you want is "openid".

**Comment by jasongroce** [comment]
Hello, we are archiving this repo and moving its content to the central Partner Center developer content location. For this scenario that's at https://learn.microsoft.com/en-us/partner-center/develop/. This feedback has been logged internally and we will use it to update the content in the future. Thank you for your feedback!
