### ISSUE TITLE
Missing documentation for Authentication

### ISSUE THREAD

**Issue by rayzorben** [MicrosoftDocs/partner-rest#14]
Documentation is severely lacking for how to authenticate for Partner Center Pricing Sheet access.

When trying to authenticate, there seem to be no details of what mechanism should be used. The URL to authenticate to, the resource to use (e.g.; https://graph.windows.net), whether or not it should be a client_credential or password authentication.

I have followed the instructions for setting up an Application with Partner Center access with user_impersonation, so I have a client id and client secret from that. But using that to get an authentication token gives access denied when trying to query for a price sheet.

I have tried every thing I have seen on the web, with no luck. I have seen people asking the same question in issues here and on stackoverflow with no clear resolution.

**Comment by jasongroce** [comment]
Hello, we are archiving this repo and moving its content to the central Partner Center developer content location. For this scenario that's at https://learn.microsoft.com/en-us/partner-center/develop/partner-center-authentication. This feedback has been logged internally and we will use it to update the content in the future. Thank you for your feedback!
