### ISSUE TITLE
Response now contains a zip file

### ISSUE THREAD

**Issue by andrepiresrep** [MicrosoftDocs/partner-rest#3]
Hello,
Since today content of the response now comes with a zip file instead of the csv file.
It would be important to mention this on the documentation.
Also what is the encoding of the zip file and the csv file?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f291738-8903-404a-4c33-5aa718b598b1
* Version Independent ID: 74502541-f1c2-dedb-89a0-bd461042b26c
* Content: [Get foreign exchange rates - Partner](https://docs.microsoft.com/en-us/partner/develop/get-foreign-exchange-rates)
* Content Source: [partner-rest/develop/get-foreign-exchange-rates.md](https://github.com/MicrosoftDocs/partner-rest/blob/docs/partner-rest/develop/get-foreign-exchange-rates.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by sansalinas** [comment]
> 
> 
> Hello,
> Since today content of the response now comes with a zip file instead of the csv file.
> It would be important to mention this on the documentation.
> Also what is the encoding of the zip file and the csv file?
> 
> Thank you.
> #### Document Details
> 
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
>     * ID: 7f291738-8903-404a-4c33-5aa718b598b1
> 
>     * Version Independent ID: 74502541-f1c2-dedb-89a0-bd461042b26c
> 
>     * Content: [Get foreign exchange rates - Partner](https://docs.microsoft.com/en-us/partner/develop/get-foreign-exchange-rates)
> 
>     * Content Source: [partner-rest/develop/get-foreign-exchange-rates.md](https://github.com/MicrosoftDocs/partner-rest/blob/docs/partner-rest/develop/get-foreign-exchange-rates.md)
> 
>     * Service: **partner-dashboard**
> 
>     * Sub-service: **partnercenter-sdk**
> 
>     * GitHub Login: @JasonWHowell
> 
>     * Microsoft Alias: **jasonh**

Accept-Encoding header is not working (If omitted file stream is not compressed.). Same issue for me

**Comment by jasongroce** [comment]
Documentation now mentions the file may be CSV or ZIP.
