### ISSUE TITLE
Error trying to obtain a valid price sheet

### ISSUE THREAD

**Issue by andrepiresrep** [MicrosoftDocs/partner-rest#4]
[Enter feedback here]
Hello, after trying to perform requests to obtain either the azure consumption price sheet and the azure reservations price sheet like so https://api.partner.microsoft.com/v1.0/sales/pricesheets(Market='gb',PricesheetView='AZURE_RESERVATIONS')/$value and https://api.partner.microsoft.com/v1.0/sales/pricesheets(Market='gb',PricesheetView='AZURE_CONSUMPTION')/$value, I am obtaining the following content on the response with a status code of 404:

 404 Web Site not found.
You may be seeing this error due to one of the reasons listed below:
Custom domain has not been configured inside Azure. See how to map an existing domain to resolve this.
Client cache is still pointing the domain to old IP address. Clear the cache by running the command ipconfig/flushdns.
Checkout App Service Domain FAQ for more questions.

Headers used:
Accept-Encoding: deflate
Authorization: Bearer 

Can you advise as to what may have changed? These were working just fine on 4th of June 2020.
Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86441aa8-87fb-4424-0335-8c6d77a0f072
* Version Independent ID: 5e462b29-f12f-e424-3b33-1cc239a793e7
* Content: [Get a price sheet - Partner](https://docs.microsoft.com/en-us/partner/develop/get-a-price-sheet)
* Content Source: [partner-rest/develop/get-a-price-sheet.md](https://github.com/MicrosoftDocs/partner-rest/blob/docs/partner-rest/develop/get-a-price-sheet.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Hi @andrepiresrep 

There was an error in this API yesterday and it should be back to working again. Sorry for the inconvenience. Please let us know if you need further assistance, and we'll take another look.

Thanks, Jason
#please-close
