### ISSUE TITLE
Outdated documentation for Partner API Create Referral

### ISSUE THREAD

**Issue by morcinim** [MicrosoftDocs/partner-rest#9]
Hello,
Can you please review the example to create a new Referral as partners report that the example in the documentation is out of date: [partner-rest](https://github.com/MicrosoftDocs/partner-rest)/[partner-rest](https://github.com/MicrosoftDocs/partner-rest/tree/docs/partner-rest)/[develop](https://github.com/MicrosoftDocs/partner-rest/tree/docs/partner-rest/develop)/create-a-referral.md

**Comment by jasongroce** [comment]
Hello, we are archiving this repo and moving its content to the central Partner Center developer content location at https://learn.microsoft.com/en-us/partner-center/develop/create-a-referral. This feedback has been logged internally and we will use it to update the content in the future.
